Repository rt-net/rt_usb_9axisimu_driver, pull requests merged in 2020-07, with the labels that each got.

#22 Refactor
  CMakeLists.txt
  include/rt_usb_9axisimu_driver/rt_usb_9axisimu.hpp
  include/rt_usb_9axisimu_driver/rt_usb_9axisimu_ascii_mode.hpp
  include/rt_usb_9axisimu_driver/rt_usb_9axisimu_binary_mode.hpp
  package.xml
  src/rt_usb_9axisimu_ascii_mode.cpp
  src/rt_usb_9axisimu_binary_mode.cpp
  src/rt_usb_9axisimu_driver.cpp
Labels: Type: Refactoring

#24 Rename files
  CMakeLists.txt
  include/rt_usb_9axisimu_driver/rt_usb_9axisimu_driver.hpp
  src/rt_usb_9axisimu_binary_mode.cpp
  src/rt_usb_9axisimu_driver.cpp
  src/rt_usb_9axisimu_driver_node.cpp
Labels: Type: Refactoring

#23 Remove "binary output mode only" description from README
  README.md
Labels: Type: Documentation

#25 Release 1.0.0
  CHANGELOG.rst
  package.xml
Labels: Type: Maintenance
